apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: template-service-broker
  name: template-service-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service-broker
  template:
    metadata:
      labels:
        app: template-service-broker
    spec:
      containers:
      - image: 172.22.11.2:30500/tsb:0.0.1
        name: tsb
        imagePullPolicy: Always
